### Top most widely used Numpy commands

In [1]:
import numpy as np

# Creating a 5x5 array
data = np.array([
    [10, 20, 30, 40, 50],
    [15, 25, 35, 45, 55],
    [20, 30, 40, 50, 60],
    [25, 35, 45, 55, 65],
    [30, 40, 50, 60, 70]
])

print("Dataset:\n", data)


Dataset:
 [[10 20 30 40 50]
 [15 25 35 45 55]
 [20 30 40 50 60]
 [25 35 45 55 65]
 [30 40 50 60 70]]


In [2]:
print("Shape of array:", data.shape)
# gives shaoe of the array 

Shape of array: (5, 5)


In [3]:
print("Total number of elements:", data.size)
# gives total number of elements 

Total number of elements: 25


In [4]:
print("Number of dimensions:", data.ndim)
# gives dimensions 

Number of dimensions: 2


In [5]:
print("Data type of array elements:", data.dtype)
#gives datatype of the elements 

Data type of array elements: int64


In [ ]:
print("Element at 0th row, 0th column:", data[0, 0])
# accessing single element 

Element at 0th row, 0th column: 10


In [ ]:
print("First column:\n", data[:, 0])
# access entire column

First column:
 [10 15 20 25 30]


In [8]:
print("First row:\n", data[0, :])
# access entire row 

First row:
 [10 20 30 40 50]


In [ ]:
print("Mean of all elements:", np.mean(data))
#gives mean of the elements print("Standard Deviation:", np.std(data))


Mean of all elements: 40.0


In [10]:
print("Median of all elements:", np.median(data))
# gives median value 

Median of all elements: 40.0


In [11]:
print("Standard Deviation:", np.std(data))
#gives standar value 

Standard Deviation: 15.811388300841896


In [12]:
print("Sum of all elements:", np.sum(data))
# gives sum of all elements 

Sum of all elements: 1000


In [13]:
print("Minimum value:", np.min(data))
#gives minimum value 

Minimum value: 10


In [14]:
print("Maximum value:", np.max(data))
#gives max value 


Maximum value: 70


In [15]:
print("Index of minimum value:", np.argmin(data))
# index of minimum value flattend

Index of minimum value: 0


In [16]:
print("Index of maximum value:", np.argmax(data))
# inex of maximum value 

Index of maximum value: 24


In [17]:
print("Sorted rows:\n", np.sort(data, axis=1))
# sort each row 

Sorted rows:
 [[10 20 30 40 50]
 [15 25 35 45 55]
 [20 30 40 50 60]
 [25 35 45 55 65]
 [30 40 50 60 70]]


In [18]:
print("Transposed array:\n", data.T)
# transpose the array 

Transposed array:
 [[10 15 20 25 30]
 [20 25 30 35 40]
 [30 35 40 45 50]
 [40 45 50 55 60]
 [50 55 60 65 70]]


In [19]:
print("Unique values:\n", np.unique(data))
# gives uniques value 

Unique values:
 [10 15 20 25 30 35 40 45 50 55 60 65 70]


In [20]:
result = np.where(data > 40)
print("Indices where value > 40:\n", result)
# where method 

Indices where value > 40:
 (array([0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4]), array([4, 3, 4, 3, 4, 2, 3, 4, 2, 3, 4]))


In [21]:
print("Clipped array (min=20, max=50):", np.clip(data, 20, 50))
# clip value 

Clipped array (min=20, max=50): [[20 20 30 40 50]
 [20 25 35 45 50]
 [20 30 40 50 50]
 [25 35 45 50 50]
 [30 40 50 50 50]]
