# Introduction for numpy
### As it is the base library for Data science 

In [1]:
import numpy as np

In [2]:
arr_1d= np.array([1,2,3,4])
arr_2d= np.array([[1,2,3,4],[4,5,6,7]])
print("1_d array=",arr_1d)
print("2_d array=",arr_2d)

1_d array= [1 2 3 4]
2_d array= [[1 2 3 4]
 [4 5 6 7]]


## List vs Numpy


In [3]:
py=[1,2,3]
print("python list multiplication=",py*2)
np =np.array([1,2,3,])
print("python array multiplication =",np*2)

python list multiplication= [1, 2, 3, 1, 2, 3]
python array multiplication = [2 4 6]


In [ ]:
import time
import numpy as np  

start = time.time()
py = [i * 2 for i in range(100000)]
print("Python List Time:", time.time() - start)

start = time.time()
npy = np.arange(100000)  
npym = npy * 2
print("NumPy Array Time:", time.time() - start)


Python List Time: 0.015559673309326172
NumPy Array Time: 0.0011491775512695312


### Making array from the scratch 


In [6]:
import numpy as np 


In [8]:
zeros=np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
ones=np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
full=np.full((2,3),7)
print(full)

[[7 7 7]
 [7 7 7]]


In [11]:
random=np.random.random((2,3))
print(random)
sequence=np.arange(0,10,2)
print(sequence )

[[0.06482997 0.97161875 0.3255573 ]
 [0.95691333 0.71569959 0.85201619]]
[0 2 4 6 8]


### Vector , matrix , tensor 

In [13]:
vector=np.array([1,2,3,4,5])
print(vector)
matrix=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(matrix)

[1 2 3 4 5]
[[1 2 3 4 5]
 [1 2 3 4 5]]
